version: 5.5.0.4
type: common
authorName: "Ilya I"
moduleName: "Klaviyo"
description: "Syncs store data, sends events, enhances email marketing."
minorRequiredCoreVersion: 0
dependsOn: {}
incompatibleWith: {}
showSettingsForm: true
canDisable: true
